{{- if gt (int .Values.replicas) 0 }}
{{- if .Values.ingress.enabled }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-wait-dns
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  restartPolicy: Never
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  containers:
    - name: {{ .Release.Name }}-wait-dns
      image: "gcr.io/kubernetes-e2e-test-images/dnsutils:1.3"
      command:
        - /bin/sh
        - -c
        - |
          MAX_INTERVALS=120
          SLEEP_INTERVAL=5
          CMD='
            echo "Attempt $i / $MAX_INTERVALS" &&
            nslookup -type=a {{ include "tezos.node.hostname" . }} &&
            current=`expr ${current:-0} + 1` || current=0 && expr $current = 3
          '
          for i in $(seq 1 $MAX_INTERVALS); do sleep $SLEEP_INTERVAL; if eval $CMD; then exit 0; fi; done; exit 1
{{- end }}
{{- end }}
